import type { ReadMode } from '../../../types/electron'

// SQLite 表名 → 中文名映射（已合并的旧表不显示）
export const TABLE_NAME_MAP: Record<string, string> = {
  projects: '项目',
  members: '人员',
  workers: '工人',
  project_workers: '用工关系',
  project_members: '项目成员',
  worker_teams: '班组',
  worker_transfer_records: '调动记录',
  departments: '部门',
  income_contracts: '收入合同',
  income_records: '收入记录',
  expense_contracts: '支出合同',
  expense_records: '支出记录',
  agreement_contracts: '协议合同',
  invoices: '发票',
  invoice_items: '发票明细',
  payment_records: '收付款',
  settlements: '结算',
  cost_ledger: '成本台账',
  cost_ledger_batches: '台账版本',
  cost_ledger_categories: '台账分类',
  cost_ledger_match_rules: '匹配规则',
  materials: '材料',
  expenses: '费用',
  drawings: '图纸',
  partners: '合作单位',
  regions: '地区',
  supervisors: '监管单位',
  templates: '模板',
  inventory_items: '库存物料',
  inventory_transactions: '出入库记录',
  wages: '工资',
  attendances: '考勤',
  salary_history: '薪资历史',
  wage_history: '工资历史',
  audit_logs: '审计日志',
  users: '用户',
  roles: '角色',
  app_config: '系统配置',
  schema_version: '架构版本',
  tasks: '任务',
  contract_templates: '合同模板',
  snapshots: '数据库快照',
}

export const readModeConfig: { mode: ReadMode; label: string; desc: string; icon: string; color: string; activeColor: string }[] = [
  {
    mode: 'dual',
    label: '双写模式',
    desc: 'SQLite 优先读取，失败回退 JSON',
    icon: 'ArrowLeftRight',
    color: 'bg-[color:var(--panel-2)]',
    activeColor: 'border-[color:var(--accent)] bg-[color:var(--accent-soft)] shadow-md',
  },
  {
    mode: 'sqlite-primary',
    label: 'SQLite 优先',
    desc: '仅从 SQLite 读取，失败报错',
    icon: 'Database',
    color: 'bg-[color:var(--panel-2)]',
    activeColor: 'border-[color:var(--accent)] bg-[color:var(--accent-soft)] shadow-md',
  },
  {
    mode: 'json-only',
    label: '仅 JSON',
    desc: '跳过 SQLite，仅使用 JSON 文件',
    icon: 'FileJson',
    color: 'bg-[color:var(--panel-2)]',
    activeColor: 'border-[color:var(--accent)] bg-[color:var(--accent-soft)] shadow-md',
  },
]

export type ReadModeLabel = typeof readModeConfig[number]['mode']
