import {
  Activity, AlertCircle, AlertTriangle, ArrowDownCircle, ArrowLeft, ArrowLeftRight, ArrowRight, ArrowRightLeft, ArrowUpCircle,
  BadgeCheck, Ban, Banknote, BarChart3, Bell, Bold, Bot, Braces, Brain, Briefcase, Building2,
  Calculator, Calendar, CalendarCheck, CalendarDays, CalendarRange, CalendarX, Camera, Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ClipboardCheck, ClipboardList, ClipboardPen, Clock, Construction, Copy, CornerDownLeft, Cpu, CreditCard,
  Code,
  Database, DollarSign, Download, Droplets,
  Edit3, Eraser, Eye, EyeOff,
  File, FileBarChart, FileCheck, FileDown, FileJson, FileSearch, FileSpreadsheet, FileText, Filter, Folder, FolderKanban, FolderOpen, FolderTree,
  GitFork, Globe,
  HardHat, Heading1, Heading2, Heading3, HeartPulse, HelpCircle, Home,
  Image, Inbox, Info, Italic,
  Key, KeyRound,
  GripVertical,
  Landmark, LayoutDashboard, Library, Lightbulb, Link, List, ListOrdered, Loader, Loader2, Lock, LogOut,
  Mail, MapPin, Menu, Maximize2, MessageSquare, Mic, Minus, Minimize2, Monitor, Moon, MoreVertical,
  Package, PaintBucket,  Paperclip, Pause, Pencil, PenLine, Phone, PieChart, Play, Plug, Plus, Power, Presentation, Printer,
  Quote,
  Receipt, Redo, Redo2, RefreshCcw, RefreshCw, RotateCcw, RotateCw, Ruler,
  Save, Scan, ScrollText, Search, SearchX, Settings, Shield, ShieldCheck, Snowflake, Sparkles, Square, SquareCheck, Stamp, Sun,
  Table, Target,
  Trash2, TrendingDown, TrendingUp, Truck, ThumbsUp, ThumbsDown,
  Undo, Undo2, Upload, User, UserCheck, UserCircle, UserCog, Users,
  Wallet, Wand2, WifiOff, Wrench,
  X, XCircle, Zap,
  type LucideIcon,
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  Activity, AlertCircle, AlertTriangle, ArrowDownCircle, ArrowLeft, ArrowLeftRight, ArrowRight, ArrowRightLeft, ArrowUpCircle,
  BadgeCheck, Ban, Banknote, BarChart3, Bell, Bold, Bot, Braces, Brain, Briefcase, Building2,
  Calculator, Calendar, CalendarCheck, CalendarDays, CalendarRange, CalendarX, Camera, Check, CheckCircle, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, ClipboardCheck, ClipboardList, ClipboardPen, Clock, Construction, Copy, CornerDownLeft, Cpu, CreditCard,
  Code,
  Database, DollarSign, Download, Droplets,
  Edit: Edit3, Edit3, Eraser, Eye, EyeOff,
  File, FileBarChart, FileCheck, FileDown, FileJson, FileSearch, FileSpreadsheet, FileText, Filter, Folder, FolderKanban, FolderOpen, FolderTree,
  GitFork, Globe,
  HardHat, Heading1, Heading2, Heading3, HeartPulse, HelpCircle, Home,
  Image, Inbox, Info, Italic,
  Key, KeyRound,
  GripVertical,
  Landmark, LayoutDashboard, Library, Lightbulb, Link, List, ListOrdered, Loader, Loader2, Lock, LogOut,
  Mail, MapPin, Menu, Maximize2, MessageSquare, Mic, Minus, Minimize2, Monitor, Moon, MoreVertical,
  Package, PaintBucket, Palette: PaintBucket, Paperclip, Pause, Pencil, PenLine, Phone, PieChart, Play, Plug, Plus, Power, Presentation, Printer,
  Quote,
  Receipt, Redo, Redo2, RefreshCcw, RefreshCw, RotateCcw, RotateCw, Ruler,
  Save, Scan, ScrollText, Search, SearchX, Settings, Shield, ShieldCheck, Snowflake, Sparkles, Square, SquareCheck, Stamp, Sun,
  Table, Target,
  Trash2, TrendingDown, TrendingUp, Truck, ThumbsUp, ThumbsDown,
  Undo, Undo2, Upload, User, UserCheck, UserCircle, UserCog, Users,
  Wallet, Wand2, WifiOff, Wrench,
  X, XCircle, Zap,
  ClipboardFile: ClipboardPen,
}

export function getIcon(name: string): LucideIcon | undefined {
  return iconMap[name]
}
