<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.19.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EngineeringManager.Api\EngineeringManager.Api.csproj" />
  </ItemGroup>

</Project>
